### post
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "ken@lucky.com",
    "password": "sldkfhj",
    "saf": "asdf"
}


### Find one particular

GET http://localhost:3000/auth/1