### post
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "ken@lucky.com",
    "password": "sldkfhj",
    "saf": "asdf"
}


### Find one particular

GET http://localhost:3000/auth/44

### Find all with email
GET http://localhost:3000/auth?email=ken@lucky.com



### Delete with id
DELETE  http://localhost:3000/auth/444


### Update user
PATCH   http://localhost:3000/auth/44
content-type: application/json

{
    "password" : "12312"
}